spring:
  profiles:
    active:
      - dev
---

server:
  port: 8080
spring:
  profiles: dev
  application:
    name: module-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver #配置MySQL的驱动程序类
#    driver-class-name: com.mysql.cj.jdbc.Driver #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
#  security:
#    user:
#      name: admin
#      password: liu123
#      roles:
#      - USER
mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  file:
    name: product.log
  level:
    root: INFO
    com.liu.mapper: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:liu123@eureka1:7001/eureka
  instance:
    instance-id: module-provider-product-8080
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

info:
  app.name: module-provider-product
  company.name: test
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$


management:
  endpoints:
    web:
      exposure:
        include: '*'

---

server:
  port: 8081
spring:
  profiles: beta
  application:
    name: module-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver #配置MySQL的驱动程序类
#    driver-class-name: com.mysql.cj.jdbc.Driver #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
#  security:
#    user:
#      name: admin
#      password: liu123
#      roles:
#      - USER
mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  file:
    name: product.log
  level:
    root: INFO
    com.liu.mapper: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:liu123@eureka1:7002/eureka
  instance:
    instance-id: module-provider-product-8080
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

info:
  app.name: module-provider-product
  company.name: test
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$


management:
  endpoints:
    web:
      exposure:
        include: '*'
